name: Dependencies

on:
  pull_request:
    paths:
      - 'package.json'

jobs:
  deps:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: projectdiscovery/actions/setup/git@v1
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun install
      - run: bun run compile
      - run: |
          git add bun.lock dist/
          git diff --quiet && git diff --staged --quiet || git commit -m "build: compile latest changes"
          git push origin $GITHUB_REF || true

  tests:
    needs: [deps]
    uses: ./.github/workflows/tests.yaml

  merge:
    needs: [deps, tests]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: projectdiscovery/actions/pr/approve@v1
      - uses: projectdiscovery/actions/pr/merge@v1
