name: Release

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch: {}

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: projectdiscovery/actions/setup/git@v1
      - uses: projectdiscovery/actions/svu-next@v1
        with:
          release-create: true
